[package]
name = "simpleton"
version = "0.35.0"
edition = "2021"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Simpleton runner for Intuicio scripting platform"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/intuicio"
repository = "https://github.com/PsichiX/intuicio"
documentation = "https://docs.rs/alchemyst"
readme = "../../README.md"
exclude = ["./resources"]

[dependencies]
intuicio-data = { version = "0.35", path = "../../platform/data" }
intuicio-core = { version = "0.35", path = "../../platform/core" }
intuicio-derive = { version = "0.35", path = "../../platform/derive" }
intuicio-backend-vm = { version = "0.35", path = "../../backends/vm" }
intuicio-frontend-simpleton = { version = "0.35", path = "../../frontends/simpleton" }
clap = { version = "4", features = ["derive"] }
dirs = "5"