[workspace]
members = [
    "platform/*",
    "backends/*",
    "frontends/*",
    "plugins/*",
    "runners/*",
    "essentials",
    "demos/tetra",
    "demos/plugin",
    "demos/emu",
    "demos/custom",
    "demos/godot-node-graph/server",
    "tests",
]
