[workspace]
members = [
    "data",
    "core",
    "tests",
    "derive",
    "backends/vm",
    "backends/rust",
    "frontends/serde",
    "frontends/assembler",
    "frontends/simpleton",
    "frontends/vault",
    "runners/simpleton",
    "demos/tetra",
]
