[package]
name = "alchemyst"
version = "0.6.1"
edition = "2021"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Alchemyst PCG tool of Intuicio scripting platform"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/intuicio"
repository = "https://github.com/PsichiX/intuicio"
documentation = "https://docs.rs/intuicio-runner-simpleton"
readme = "../../README.md"

[lib]
path = "src/lib.rs"

[[bin]]
name = "alchemyst"
path = "src/main.rs"

[features]
default = ["console", "fs", "jobs"]
console = ["intuicio-frontend-simpleton/console"]
fs = ["intuicio-frontend-simpleton/fs"]
jobs = ["intuicio-frontend-simpleton/jobs"]

[dependencies]
intuicio-data = { version = "0.6", path = "../../platform/data" }
intuicio-core = { version = "0.6", path = "../../platform/core" }
intuicio-derive = { version = "0.6", path = "../../platform/derive" }
intuicio-backend-vm = { version = "0.6", path = "../../backends/vm" }
image = "0.24"
vek = "0.15"
clap = { version = "4", features = ["derive"] }

[dependencies.intuicio-frontend-simpleton]
version = "0.6"
path = "../../frontends/simpleton"
default-features = false
