[package]
name = "alchemyst"
version = "0.27.1"
edition = "2021"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Alchemyst PCG tool based on Intuicio scripting platform"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/intuicio"
repository = "https://github.com/PsichiX/intuicio"
documentation = "https://docs.rs/alchemyst"
readme = "../../README.md"
exclude = ["./resources"]

[dependencies]
intuicio-data = { version = "0.27", path = "../../platform/data" }
intuicio-core = { version = "0.27", path = "../../platform/core" }
intuicio-derive = { version = "0.27", path = "../../platform/derive" }
intuicio-backend-vm = { version = "0.27", path = "../../backends/vm" }
image = "0.24"
vek = "0.16"
clap = { version = "4", features = ["derive"] }
dirs = "5"

[dependencies.intuicio-frontend-simpleton]
version = "0.27"
path = "../../frontends/simpleton"
default-features = false
features = ["console", "fs", "jobs", "plugins"]
