[package]
name = "tetra-integration"
version = "0.5.1"
edition = "2021"
publish = false

[dependencies]
intuicio-data = { version = "0.5", path = "../../data" }
intuicio-core = { version = "0.5", path = "../../core" }
intuicio-derive = { version = "0.5", path = "../../derive" }
intuicio-backend-vm = { version = "0.5", path = "../../backends/vm" }
intuicio-frontend-simpleton = { version = "0.5", path = "../../frontends/simpleton" }
tetra = { version = "0.7", features = ["sdl2_bundled"] }
toml = "0.7"
serde = "1"