list:
    just --list

package:
    cargo run --release --bin packager -- manifest.toml cartridge.bin

run:
    cargo run --release --bin emulator -- cartridge.bin

package-run:
    just package
    just run