[package]
name = "godot-node-graph-server"
version = "0.11.1"
edition = "2021"
publish = false

[dependencies]
intuicio-core = { version = "0.11", path = "../../../platform/core" }
intuicio-nodes = { version = "0.11", path = "../../../platform/nodes" }
intuicio-frontend-assembler = { version = "0.11", path = "../../../frontends/assembler" }
websocket = "0.24"
clap = { version = "4", features = ["derive"] }
serde = "1"
serde_json = "1"
