[package]
name = "benches"
version = "0.33.5"
edition = "2021"
publish = false

[features]
bench_access = []
bench_allocator = []
bench_div = []
bench_ecs = []
bench_fib = []
bench_misc = []
bench_sqrt = []
bench_all = [
    "bench_access",
    "bench_allocator",
    "bench_div",
    "bench_ecs",
    "bench_fib",
    "bench_misc",
    "bench_sqrt",
]
default = ["bench_all"]

[dependencies]
intuicio-data = { version = "0.33", path = "../platform/data" }
intuicio-core = { version = "0.33", path = "../platform/core" }
intuicio-backend-vm = { version = "0.33", path = "../backends/vm" }
intuicio-frontend-vault = { version = "0.33", path = "../frontends/vault" }
intuicio-framework-ecs = { version = "0.33", path = "../frameworks/ecs" }
rune = "*"
rune-modules = "*"
rhai = "*"
hecs = "*"
